[package]
name = "dudes_in_space"
version = "0.0.1"
edition = "2024"

[dependencies]
sdl2 = "0.37.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.1"
serde_json = "1.0"
serde-intermediate = "1.0.0"
dudes_in_space_macro = { path = "./macro"}