[package]
name = "dyn_serde_macro"
version = "0.0.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.104"
quote = "1.0.40"
proc-macro2 = "1.0.95"
convert_case = "0.8.0"
darling = "0.21.0"
